env:
  global:
    - secure: RbRoGpIx2UsYu65WStM8gapZMNi1Wi/1p9EFdPck6pYw0oJ0VueDqXjklbmZBWQpRNLHArph/WQGPXt/Ao3VyQsj5FPTzyMyYZv0naFCPrWoUo0oRTv0KkWMkxKSd0fR42ef7dZF9OOlrvgjf3GR5mzJmsLy11YFP6BccJJUNwU=

language: python

branches:
  only:
    - master

before_install:
  - pip install sphinx
  - pip install sphinx_bootstrap_theme

install:
  - make html
  - make latexpdf
  - make epub

script:
  - bash -x ./travis_deploy.sh
